services:
  db:
    image: mysql:8.0
    container_name: mihirunk_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: L6Ndk3o
      MYSQL_DATABASE: MiHirunk_DB
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mihirunk_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: L6Ndk3o
      PMA_ABSOLUTE_URI: http://localhost/phpmyadmin/
    depends_on:
      - db

  backend:
    container_name: mihirunk_backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: L6Ndk3o
      DB_NAME: MiHirunk_DB
      DB_DIALECT: mysql
      NODE_ENV: production
      Docker_Active: true
      PORT: 6769
      HOST: 0.0.0.0
    volumes:
      - backend_uploads:/app/public/cloud
    command: npm run start:production
    depends_on:
      db:
        condition: service_healthy

  frontend:
    container_name: mihirunk_frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - VITE_API_URL=/api

  #nginx or treafik reverse proxy, open port 80 or 443
  nginx-proxy:
    image: nginx:alpine
    container_name: mihirunk_nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"   # IDE jön minden külső kérés
    volumes:
      - ./nginx-proxy/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
      - phpmyadmin

volumes:
  db_data:
  backend_uploads:
