/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegistrationIndexRouteImport } from './routes/registration/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as RegistrationTokenIndexRouteImport } from './routes/registration/$token/index'
import { Route as ProfilProfilIdIndexRouteImport } from './routes/profil/$profilId/index'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationIndexRoute = RegistrationIndexRouteImport.update({
  id: '/registration/',
  path: '/registration/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationTokenIndexRoute = RegistrationTokenIndexRouteImport.update({
  id: '/registration/$token/',
  path: '/registration/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilProfilIdIndexRoute = ProfilProfilIdIndexRouteImport.update({
  id: '/profil/$profilId/',
  path: '/profil/$profilId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/friends': typeof FriendsRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/login': typeof LoginIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/profil/$profilId': typeof ProfilProfilIdIndexRoute
  '/registration/$token': typeof RegistrationTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/friends': typeof FriendsRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/login': typeof LoginIndexRoute
  '/registration': typeof RegistrationIndexRoute
  '/profil/$profilId': typeof ProfilProfilIdIndexRoute
  '/registration/$token': typeof RegistrationTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/friends': typeof FriendsRoute
  '/news': typeof NewsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/login/': typeof LoginIndexRoute
  '/registration/': typeof RegistrationIndexRoute
  '/profil/$profilId/': typeof ProfilProfilIdIndexRoute
  '/registration/$token/': typeof RegistrationTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/friends'
    | '/news'
    | '/privacy'
    | '/settings'
    | '/test'
    | '/login'
    | '/registration'
    | '/profil/$profilId'
    | '/registration/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/friends'
    | '/news'
    | '/privacy'
    | '/settings'
    | '/test'
    | '/login'
    | '/registration'
    | '/profil/$profilId'
    | '/registration/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/friends'
    | '/news'
    | '/privacy'
    | '/settings'
    | '/test'
    | '/login/'
    | '/registration/'
    | '/profil/$profilId/'
    | '/registration/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FriendsRoute: typeof FriendsRoute
  NewsRoute: typeof NewsRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  TestRoute: typeof TestRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegistrationIndexRoute: typeof RegistrationIndexRoute
  ProfilProfilIdIndexRoute: typeof ProfilProfilIdIndexRoute
  RegistrationTokenIndexRoute: typeof RegistrationTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/': {
      id: '/registration/'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration/$token/': {
      id: '/registration/$token/'
      path: '/registration/$token'
      fullPath: '/registration/$token'
      preLoaderRoute: typeof RegistrationTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$profilId/': {
      id: '/profil/$profilId/'
      path: '/profil/$profilId'
      fullPath: '/profil/$profilId'
      preLoaderRoute: typeof ProfilProfilIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FriendsRoute: FriendsRoute,
  NewsRoute: NewsRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  TestRoute: TestRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegistrationIndexRoute: RegistrationIndexRoute,
  ProfilProfilIdIndexRoute: ProfilProfilIdIndexRoute,
  RegistrationTokenIndexRoute: RegistrationTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
