/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsPrivacyRouteImport } from './routes/settings/privacy'
import { Route as SettingsNotificationRouteImport } from './routes/settings/notification'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as AloldalakPrivacyRouteImport } from './routes/_aloldalak/privacy'
import { Route as AloldalakNewsRouteImport } from './routes/_aloldalak/news'
import { Route as AloldalakAboutRouteImport } from './routes/_aloldalak/about'
import { Route as ProfilProfilIdIndexRouteImport } from './routes/profil/$profilId/index'
import { Route as AuthRegistrationIndexRouteImport } from './routes/_auth/registration/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthRegistrationTokenIndexRouteImport } from './routes/_auth/registration/$token/index'

const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsPrivacyRoute = SettingsPrivacyRouteImport.update({
  id: '/settings/privacy',
  path: '/settings/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationRoute = SettingsNotificationRouteImport.update({
  id: '/settings/notification',
  path: '/settings/notification',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/settings/account',
  path: '/settings/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AloldalakPrivacyRoute = AloldalakPrivacyRouteImport.update({
  id: '/_aloldalak/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AloldalakNewsRoute = AloldalakNewsRouteImport.update({
  id: '/_aloldalak/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const AloldalakAboutRoute = AloldalakAboutRouteImport.update({
  id: '/_aloldalak/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilProfilIdIndexRoute = ProfilProfilIdIndexRouteImport.update({
  id: '/profil/$profilId/',
  path: '/profil/$profilId/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistrationIndexRoute = AuthRegistrationIndexRouteImport.update({
  id: '/_auth/registration/',
  path: '/registration/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegistrationTokenIndexRoute =
  AuthRegistrationTokenIndexRouteImport.update({
    id: '/_auth/registration/$token/',
    path: '/registration/$token/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/about': typeof AloldalakAboutRoute
  '/news': typeof AloldalakNewsRoute
  '/privacy': typeof AloldalakPrivacyRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/notification': typeof SettingsNotificationRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings': typeof SettingsIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/registration': typeof AuthRegistrationIndexRoute
  '/profil/$profilId': typeof ProfilProfilIdIndexRoute
  '/registration/$token': typeof AuthRegistrationTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/about': typeof AloldalakAboutRoute
  '/news': typeof AloldalakNewsRoute
  '/privacy': typeof AloldalakPrivacyRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/notification': typeof SettingsNotificationRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings': typeof SettingsIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/registration': typeof AuthRegistrationIndexRoute
  '/profil/$profilId': typeof ProfilProfilIdIndexRoute
  '/registration/$token': typeof AuthRegistrationTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connections': typeof ConnectionsRoute
  '/_aloldalak/about': typeof AloldalakAboutRoute
  '/_aloldalak/news': typeof AloldalakNewsRoute
  '/_aloldalak/privacy': typeof AloldalakPrivacyRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/notification': typeof SettingsNotificationRoute
  '/settings/privacy': typeof SettingsPrivacyRoute
  '/settings/': typeof SettingsIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/_auth/registration/': typeof AuthRegistrationIndexRoute
  '/profil/$profilId/': typeof ProfilProfilIdIndexRoute
  '/_auth/registration/$token/': typeof AuthRegistrationTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connections'
    | '/about'
    | '/news'
    | '/privacy'
    | '/settings/account'
    | '/settings/notification'
    | '/settings/privacy'
    | '/settings'
    | '/login'
    | '/registration'
    | '/profil/$profilId'
    | '/registration/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connections'
    | '/about'
    | '/news'
    | '/privacy'
    | '/settings/account'
    | '/settings/notification'
    | '/settings/privacy'
    | '/settings'
    | '/login'
    | '/registration'
    | '/profil/$profilId'
    | '/registration/$token'
  id:
    | '__root__'
    | '/'
    | '/connections'
    | '/_aloldalak/about'
    | '/_aloldalak/news'
    | '/_aloldalak/privacy'
    | '/settings/account'
    | '/settings/notification'
    | '/settings/privacy'
    | '/settings/'
    | '/_auth/login/'
    | '/_auth/registration/'
    | '/profil/$profilId/'
    | '/_auth/registration/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectionsRoute: typeof ConnectionsRoute
  AloldalakAboutRoute: typeof AloldalakAboutRoute
  AloldalakNewsRoute: typeof AloldalakNewsRoute
  AloldalakPrivacyRoute: typeof AloldalakPrivacyRoute
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsNotificationRoute: typeof SettingsNotificationRoute
  SettingsPrivacyRoute: typeof SettingsPrivacyRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegistrationIndexRoute: typeof AuthRegistrationIndexRoute
  ProfilProfilIdIndexRoute: typeof ProfilProfilIdIndexRoute
  AuthRegistrationTokenIndexRoute: typeof AuthRegistrationTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/privacy': {
      id: '/settings/privacy'
      path: '/settings/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof SettingsPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notification': {
      id: '/settings/notification'
      path: '/settings/notification'
      fullPath: '/settings/notification'
      preLoaderRoute: typeof SettingsNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_aloldalak/privacy': {
      id: '/_aloldalak/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AloldalakPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_aloldalak/news': {
      id: '/_aloldalak/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AloldalakNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_aloldalak/about': {
      id: '/_aloldalak/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AloldalakAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$profilId/': {
      id: '/profil/$profilId/'
      path: '/profil/$profilId'
      fullPath: '/profil/$profilId'
      preLoaderRoute: typeof ProfilProfilIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/registration/': {
      id: '/_auth/registration/'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof AuthRegistrationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/registration/$token/': {
      id: '/_auth/registration/$token/'
      path: '/registration/$token'
      fullPath: '/registration/$token'
      preLoaderRoute: typeof AuthRegistrationTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectionsRoute: ConnectionsRoute,
  AloldalakAboutRoute: AloldalakAboutRoute,
  AloldalakNewsRoute: AloldalakNewsRoute,
  AloldalakPrivacyRoute: AloldalakPrivacyRoute,
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsNotificationRoute: SettingsNotificationRoute,
  SettingsPrivacyRoute: SettingsPrivacyRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegistrationIndexRoute: AuthRegistrationIndexRoute,
  ProfilProfilIdIndexRoute: ProfilProfilIdIndexRoute,
  AuthRegistrationTokenIndexRoute: AuthRegistrationTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
