/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminPanelIndexRouteImport } from './routes/AdminPanel/index'
import { Route as RegisterTokenIndexRouteImport } from './routes/register/$token/index'
import { Route as ProfilProfilIdIndexRouteImport } from './routes/profil/$profilId/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPanelIndexRoute = AdminPanelIndexRouteImport.update({
  id: '/AdminPanel/',
  path: '/AdminPanel/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterTokenIndexRoute = RegisterTokenIndexRouteImport.update({
  id: '/register/$token/',
  path: '/register/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilProfilIdIndexRoute = ProfilProfilIdIndexRouteImport.update({
  id: '/profil/$profilId/',
  path: '/profil/$profilId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/settings': typeof SettingsRoute
  '/AdminPanel': typeof AdminPanelIndexRoute
  '/profil/$profilId': typeof ProfilProfilIdIndexRoute
  '/register/$token': typeof RegisterTokenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/settings': typeof SettingsRoute
  '/AdminPanel': typeof AdminPanelIndexRoute
  '/profil/$profilId': typeof ProfilProfilIdIndexRoute
  '/register/$token': typeof RegisterTokenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/friends': typeof FriendsRoute
  '/settings': typeof SettingsRoute
  '/AdminPanel/': typeof AdminPanelIndexRoute
  '/profil/$profilId/': typeof ProfilProfilIdIndexRoute
  '/register/$token/': typeof RegisterTokenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/friends'
    | '/settings'
    | '/AdminPanel'
    | '/profil/$profilId'
    | '/register/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/friends'
    | '/settings'
    | '/AdminPanel'
    | '/profil/$profilId'
    | '/register/$token'
  id:
    | '__root__'
    | '/'
    | '/friends'
    | '/settings'
    | '/AdminPanel/'
    | '/profil/$profilId/'
    | '/register/$token/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRoute: typeof FriendsRoute
  SettingsRoute: typeof SettingsRoute
  AdminPanelIndexRoute: typeof AdminPanelIndexRoute
  ProfilProfilIdIndexRoute: typeof ProfilProfilIdIndexRoute
  RegisterTokenIndexRoute: typeof RegisterTokenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminPanel/': {
      id: '/AdminPanel/'
      path: '/AdminPanel'
      fullPath: '/AdminPanel'
      preLoaderRoute: typeof AdminPanelIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/$token/': {
      id: '/register/$token/'
      path: '/register/$token'
      fullPath: '/register/$token'
      preLoaderRoute: typeof RegisterTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil/$profilId/': {
      id: '/profil/$profilId/'
      path: '/profil/$profilId'
      fullPath: '/profil/$profilId'
      preLoaderRoute: typeof ProfilProfilIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRoute: FriendsRoute,
  SettingsRoute: SettingsRoute,
  AdminPanelIndexRoute: AdminPanelIndexRoute,
  ProfilProfilIdIndexRoute: ProfilProfilIdIndexRoute,
  RegisterTokenIndexRoute: RegisterTokenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
